f = open("Day-10/file.txt",'r')
readOperation = f.read()
print(readOperation)
f.close()
f = open("Day-10/file.txt",'r')
readLineOperation = f.readline()
print(readLineOperation)
f.close()
f = open("Day-10/file.txt",'r')
readLinesOperation = f.readlines()
print(readLinesOperation)
f.close()
